name: Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          npm install --no-ansi --no-interaction
          npm run build
      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

  deploy-and-build:
    needs: backend-test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Deploy And Build

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /var/www/html/my-site
            git checkout -f
            git pull origin main

            php artisan down

            composer install --optimize-autoloader
            php artisan migrate --force
            # sudo chown -R $USER:www-data storage
            # sudo chown -R $USER:www-data bootstrap/cache
            # chmod -R 775 storage bootstrap/cache

            #frontend assets
            npm run build

            # CACHE ASSETS
            php artisan optimize
